import fs from 'fs';
import path from 'path';

export interface BlogMetadata {
  slug: string;
  title: string;
  excerpt: string;
  date: string;
  author: string;
  tags: string[];
  readTime: string;
}

// Parse markdown's frontmatter.
function parseFrontmatter(markdown: string): { metadata: BlogMetadata; content: string } {
  const frontmatterRegex = /^---\n([\s\S]*?)\n---\n([\s\S]*)$/;
  const match = markdown.match(frontmatterRegex);
  
  if (!match) {
    throw new Error('Invalid markdown format: missing frontmatter');
  }
  
  const [, frontmatter, content] = match;
  const metadata = {} as any;
  
  frontmatter.split('\n').forEach(line => {
    const [key, ...valueParts] = line.split(':');
    if (key && valueParts.length > 0) {
      const value = valueParts.join(':').trim();
      
      if (value.startsWith('[') && value.endsWith(']')) {
        const arrayContent = value.slice(1, -1);
        metadata[key.trim()] = arrayContent.split(',').map(item => item.trim());
      } else {
        metadata[key.trim()] = value;
      }
    }
  });
  
  return {
    metadata: metadata,
    content: content.trim()
  };
}


// Define paths
const postsDir = path.join(process.cwd(), 'blog');
const outputDir = path.join(process.cwd(), 'src', 'generated'); // Output to src/generated
const outputFile = path.join(outputDir, 'blog-data.ts');

console.log('🚀 Starting post conversion script...');

// Helper function to calculate reading time
function calculateReadTime(content) {
  const wordsPerMinute = 200;
  const wordCount = content.split(/\s+/).length;
  const minutes = Math.ceil(wordCount / wordsPerMinute);
  return `${minutes} min read`;
}

// Ensure the output directory exists
if (!fs.existsSync(outputDir)) {
  fs.mkdirSync(outputDir, { recursive: true });
}

try {
  const filenames = fs.readdirSync(postsDir);

  const allPosts = filenames
    .filter((filename) => path.extname(filename) === '.md')
    .map((filename) => {
      const slug = filename.replace(/\.md$/, '');
      const fullPath = path.join(postsDir, filename);
      const fileContents = fs.readFileSync(fullPath, 'utf8');
      const { metadata, content } = parseFrontmatter(fileContents);
      const readTime = calculateReadTime(content);

      return {
        slug,
        content,
        title: metadata.title,
        excerpt: metadata.excerpt,
        date: metadata.date,
        author: metadata.author,
        tags: metadata.tags,
        readTime,
      };
    });

  // Sort posts by date in descending order
  allPosts.sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime());
  
  // Create the file content as a JavaScript module
  const fileContent = `// This file is auto-generated by scripts/build-blog.ts
export interface BlogPost {
  slug: string;
  title: string;
  excerpt: string;
  content: string;
  date: string;
  author: string;
  tags: string[];
  readTime: string;
}

export const allPosts: BlogPost[] = ${JSON.stringify(allPosts, null, 2)};
`;

  // Write the file
  fs.writeFileSync(outputFile, fileContent);

  console.log(`✅ Successfully converted ${allPosts.length} posts to ${outputFile}`);

} catch (error) {
  console.error('❌ Error during post conversion:', error);
  process.exit(1); // Exit with an error code
}
